### PR TITLE
use FindFirstFile to get proper module name casing

### PR DESCRIPTION
**Pull request by nadako**
use FindFirstFile to get proper module name casing instead of GetShortPathName+GetLongPathName, as those won't work with 8.3 names disabled (see HaxeFoundation/haxe#3779)

### CODE REVIEW

**Comment by ncannasse** [comment]
Are you sure it handles all the cases ? We need to check things such as -cp not matching the actual filesystem case, etc.

**Comment by ncannasse** [comment]
I'm telling you this because I have been fighting with this function for years :)

**Comment by nadako** [comment]
It would be great to know exactly what are these `all cases` are :-) But anyway, `FindFirstFile` apparently doesn't work on directories, only files, so for directories it's the same as calling `GetFullPathName`.

Everything seems to work for me, but surely I'd like to see what AppVeyor thinks about it.

**Comment by ncannasse** [comment]
Well we don't have all the unit tests for it because it's windows specific AND might depend on the partition (8.3 names disabled for instance). But if it does not resolve directory names then it's not enough. We need to make sure that get_full_path "D:/PaTh/tO/myDir/fiLE.hx" == get_full_path "d:/Path/to/myDir/File.hx"

**Comment by nadako** [comment]
I hoped that resolving module file name would be enough as otherwise we have to do much more work. I'll try to find some solution...

**Comment by nadako** [comment]
Please check out the latest version! It's based on http://stackoverflow.com/questions/74451/getting-actual-file-name-with-proper-casing-on-windows, but is more lightweight.

I tested it with both existent and non-existent paths, different slashes, trailing slashes, etc and it seems to handle all cases.

**Comment by ncannasse** [comment]
Ok, let's give it a try !

**Comment by Simn** [comment]
Is it really necessary to change this in the RC phase...?

**Comment by nadako** [comment]
There are more and more windows systems with 8dot3names just disabled and breaking completion because of that isn't really an option, is it?

**Pull request merged**
