### PR TITLE
Fix for --times on OSX & linux under reporting time.

### PR DESCRIPTION
**Pull request by thomasuster**

### CODE REVIEW

**Comment by jcward** [comment]
FYI, on Linux, I got undefined `clock_gettime` and `CLOCK_MONOTONIC_RAW` until I also added `include <time.h>` on line [about line 36](https://github.com/thomasuster/ocamllibs/blob/21e565bdc99f7e9836ba145018d68e82e481a2ac/extc/extc_stubs.c#L36) -- according to [this man page](https://linux.die.net/man/3/clock_gettime) `time.h` provides those (on OSX, maybe sys/time.h also inclues time.h?).

After that, I agree, this seems to be reporting realtime of the cpp compiler:

image

**Comment by thomasuster** [comment]
@jcward Cool thanks for testing. Added

**Comment by Simn** [comment]
This fails on our CI:

```
extc_stubs.c:498:16: error: use of undeclared identifier 'CLOCK_MONOTONIC_RAW'
        clock_gettime(CLOCK_MONOTONIC_RAW, &t);
```

**Comment by jcward** [comment]
Interesting, that run included the `time.h` update and passed the linux worker, but failed on the OSX worker.

When I google OSX clock_gettime, I see mostly "not supported on OSX" -- so @thomasuster, how is it working for you?

**Comment by thomasuster** [comment]
@Simn Fixed, apparently some OSX versions don't support it. My macbook happens to be able to compile / run either.

@jcward It does work on some versions of OSX, apparently mine is one of them.

**Comment by Simn** [comment]
I know nothing about time handling on OS X and Linux, so I'll have to trust you guys (and our CI) on this.

**Pull request merged**
